[package]
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
name = "hsl-weever"
version = "0.1.1-pre"
edition = "2018"

[dependencies]
chrono = "0.2"
clap = "2.19.3"
hyper = "0.10"
percent-encoding = "2.1"
regex = "1.4"
rustc-serialize = "0.3.22"
url = "2.2"
